"""add daily_progress to tasks

Revision ID: 1e4847f4400e
Revises: d64523c8af15
Create Date: 2026-08-17 13:26:52.426216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4847f4400e'
down_revision = 'd64523c8af15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('daily_progress', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'daily_progress')
    # ### end Alembic commands ###
