"""add budget months categories expenses

Revision ID: 48f5e5ac8b99
Revises: 8007de5f4ad8
Create Date: 2026-08-22 01:54:51.880438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f5e5ac8b99'
down_revision = '8007de5f4ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_months',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('savings_mode', sa.String(length=10), nullable=False),
    sa.Column('savings_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_budget_user_year_month')
    )
    op.create_index(op.f('ix_budget_months_user_id'), 'budget_months', ['user_id'], unique=False)
    op.create_table('budget_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_month_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('input_mode', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['budget_month_id'], ['budget_months.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_categories_budget_month_id'), 'budget_categories', ['budget_month_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_category_id'], ['budget_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_budget_category_id'), 'expenses', ['budget_category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_budget_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_budget_categories_budget_month_id'), table_name='budget_categories')
    op.drop_table('budget_categories')
    op.drop_index(op.f('ix_budget_months_user_id'), table_name='budget_months')
    op.drop_table('budget_months')
    # ### end Alembic commands ###
