"""add is_default to budget_categories

Revision ID: 496d2a2a890a
Revises: 48f5e5ac8b99
Create Date: 2026-08-24 15:21:45.109458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496d2a2a890a'
down_revision = '48f5e5ac8b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('is_default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_categories', 'is_default')
    # ### end Alembic commands ###
