"""add is_default to budget_categories

Revision ID: 57405ded2537
Revises: b1b8b575942a
Create Date: 2026-08-26 00:46:43.822588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57405ded2537'
down_revision = 'b1b8b575942a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
