"""add habits and habit_logs

Revision ID: 59e8f888ed6f
Revises: 70e70992a953
Create Date: 2026-08-20 02:06:31.230576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e8f888ed6f'
down_revision = '70e70992a953'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
