"""add workout frequency to preferences

Revision ID: 8007de5f4ad8
Revises: 59e8f888ed6f
Create Date: 2026-08-21 01:33:45.732188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8007de5f4ad8'
down_revision = '59e8f888ed6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('workout_frequency_type', sa.String(length=10), nullable=False, server_default='weekly'))
    op.add_column('user_preferences', sa.Column('workout_frequency_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'workout_frequency_count')
    op.drop_column('user_preferences', 'workout_frequency_type')
    # ### end Alembic commands ###
