"""add gender, fitness_goal, whatsapp unique

Revision ID: 862b932b17eb
Revises: 9f6d4f36c8b6
Create Date: 2026-08-15 02:23:49.166649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862b932b17eb'
down_revision = '9f6d4f36c8b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('gender', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_users_whatsapp_number'), 'users', ['whatsapp_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_whatsapp_number'), table_name='users')
    op.drop_column('user_preferences', 'gender')
    # ### end Alembic commands ###
