"""add hours_per_day to study_goals

Revision ID: 9a434b7e2b40
Revises: 57405ded2537
Create Date: 2026-09-11 18:24:06.299493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a434b7e2b40'
down_revision = '57405ded2537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_goals', sa.Column('hours_per_day', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_goals', 'hours_per_day')
    # ### end Alembic commands ###
