"""add is_default to budget_categories

Revision ID: b1b8b575942a
Revises: 496d2a2a890a
Create Date: 2026-08-25 13:13:25.521109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b8b575942a'
down_revision = '496d2a2a890a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
